V3_Movie_MVC_RepoPattern_EF_CodeFirst_Identity/Controllers/ActorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using V3_Movie_MVC_RepoPattern_EF_CodeFirst_Identity.Data;
using V3_Movie_MVC_RepoPattern_EF_CodeFirst_Identity.Models;
using V3_Movie_MVC_RepoPattern_EF_CodeFirst_Identity.ViewModels;

namespace V3_Movie_MVC_RepoPattern_EF_CodeFirst_Identity.Controllers
{
    public class ActorsController : Controller
    {
        IRepository repository;
        public ActorsController(IRepository repository)
        {
            this.repository = repository;
        }
        // GET: Actors
        public ActionResult Index()
        {
            return View(repository.GetActors());
        }

        // GET: Actors/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Actors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Actors/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Actor actor )
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    bool result = repository.AddActor(actor);
                    if (result)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    
                        return View();
                    
                }

                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: Actors/Edit/5
        public ActionResult Edit(int id)
        {
            var actor = repository.GetActorById(id);
            if(actor==null)
            {
                return NotFound();
            }
            return View(actor);
        }

        // POST: Actors/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Actor actor)
        {
            try
            {
                // TODO: Add update logic here
                if(!ModelState.IsValid)
                {
                    return View();
                }
                if(id != actor.Id)
                {
                    return View();
                }
                bool result = repository.EditActor(actor);
                if(result)
                {
                    return RedirectToAction(nameof(Index));
                }

                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: Actors/Delete/5
        public ActionResult Delete(int id)
        {
            var actor = repository.GetActorById(id);
            if(actor==null)
            {
                return NotFound();
            }
            return View(actor);
        }

        // POST: Actors/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                var actor = repository.GetActorById(id);
                if (actor != null)
                {
                    bool result = repository.DeleteActor(actor);
                    if(result)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    
                }
               

                return View();
            }
            catch
            {
                return View();
            }
        }
        public ActionResult GetActorsByGender()
        {
            return View();
        }
        [HttpPost]
        public ActionResult GetActorsByGender(Gender gender)
        {
            var list = repository.GetActorsByGender(gender);
            return View(list);
        }
        public ActionResult GetActorsByMovie()
        {
            var viewModel = new MovieActorsViewModel
            {
                Movies = repository.GetMovies().Select(m =>
                        new SelectListItem(m.Name, m.Id.ToString())).ToList()
            };
            
            return View(viewModel);
        }
        [HttpPost]
        public ActionResult GetActorsByMovie(int id)
        {
            var viewModel = new MovieActorsViewModel
            {
                Movies = repository.GetMovies().Select(m =>
                        new SelectListItem(m.Name, m.Id.ToString())).ToList(),
                Actors = repository.GetActorsByMovie(id)
            };
            return View(viewModel);
        }
    }
}

V3_Movie_MVC_RepoPattern_EF_CodeFirst_Identity/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using V3_Movie_MVC_RepoPattern_EF_CodeFirst_Identity.Data;
using V3_Movie_MVC_RepoPattern_EF_CodeFirst_Identity.Models;
using V3_Movie_MVC_RepoPattern_EF_CodeFirst_Identity.ViewModels;

namespace V3_Movie_MVC_RepoPattern_EF_CodeFirst_Identity.Controllers
{
    public class MoviesController : Controller
    {
        IRepository repository = null;
        public MoviesController(IRepository repository)
        {
            this.repository = repository;
        }

        // GET: Movies
        public ActionResult Index()
        {
            return View(repository.GetMovies());
        }

        // GET: Movies/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Movies/Create
        public ActionResult Create()
        {
            var viewModel = new MovieViewModel
            {
                Actors = repository.GetActors().Select(a =>
                         new SelectListItem(a.Name, a.Id.ToString())).ToList()
            };
            return View(viewModel);
        }

        // POST: Movies/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MovieViewModel viewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    bool result = repository.AddMovie(viewModel);
                    if (result)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
                viewModel = new MovieViewModel
                {
                    Actors = repository.GetActors().Select(a => new SelectListItem(a.Name, a.Id.ToString())).ToList()
                };
                

                return View(viewModel);
            }
            catch
            {
                return View();
            }
        }

        // GET: Movies/Edit/5
        public ActionResult Edit(int id)
        {
            var movie = repository.GetMovieById(id);
            if (movie == null)
            {
                return NotFound();
            }
            var viewModel = new MovieViewModel
            {
                Movie = movie,
                Actors = repository.GetActors().Select(a =>
                new SelectListItem(a.Name, a.Id.ToString(),a.Movie?.Id == movie.Id ? true:false)).ToList()
            };
            return View(viewModel);
        }

        // POST: Movies/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, MovieViewModel viewModel)
        {
            try
            {

                if (ModelState.IsValid && id == viewModel.Movie.Id)
                {

                    bool result = repository.EditMovie(viewModel);
                    if (result)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
                var movie = repository.GetMovieById(id);

                viewModel = new MovieViewModel
                {
                    Movie = movie,
                    Actors = repository.GetActors().Select(a => new SelectListItem(a.Name, a.Id.ToString(), a.Movie?.Id == movie.Id ? true : false)).ToList()
                };
                return View(viewModel);

            }
            catch
            {
                var movie = repository.GetMovieById(id);

                viewModel = new MovieViewModel
                {
                    Movie = movie,
                    Actors = repository.GetActors().Select(a => new SelectListItem(a.Name, a.Id.ToString(), a.Movie?.Id == movie.Id ? true : false)).ToList()
                };
                return View(viewModel);
            }
        }

        // GET: Movies/Delete/5
        public ActionResult Delete(int id)
        {
            var movie = repository.GetMovieById(id);
            if(movie==null)
            {
                return NotFound();
            }
            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                bool result = repository.DeleteMovie(id);
                if (result )
                {
                    return RedirectToAction(nameof(Index));
                }
                return View(repository.GetMovieById(id));
            }
            catch
            {
                return View();
            }
        }
    }
}

V3_Movie_MVC_RepoPattern_EF_CodeFirst_Identity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - V3_Movie_MVC_RepoPattern_EF_CodeFirst_Identity</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Movies" asp-action="Index"><h4>Movie App</h4></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index">Movies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Actors" asp-action="Index">Actors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Actors" asp-action="Create">Add Actors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Actors" asp-action="GetActorsByGender">Search Actors By Gender</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Actors" asp-action="GetActorsByMovie">Search Actors By Movies</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - V3_Movie_MVC_RepoPattern_EF_CodeFirst_Identity - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>